networks:
  caddy_network:
    name: caddy_network
    external: true
services:
  epaper-nice:
    networks:
      - caddy_network
    restart: unless-stopped
    volumes:
      - ./extensions:/home/iot/extensions # mounting local extensions.epaper package (includes resources/)
      - ./main.py:/home/iot/main.py # standalone entry point
      - ./data:/home/iot/data
    build: 
      context: .
      args:
        - PUID=1003 # change this to your user id
        - PGID=1003 # change this to your group id
