networks:
  caddy_network:
    name: caddy_network
    external: true
services:
  epaper-nice:
    networks:
      - caddy_network
    restart: unless-stopped
    volumes:
      - ./app:/home/iot/app # mounting local app directory
      - ./data:/home/iot/data
      - ./resources:/home/iot/resources
    build: 
      context: .
      args:
        - PUID=1003 # change this to your user id
        - PGID=1003 # change this to your group id
