"""
Standalone entry point: uvicorn main:app --reload

Assembles its own FastAPI app and NiceGUI pages from the same reusable
extensions.epaper.* code the nice4iot extension uses (see
extensions/epaper/__init__.py's register(app) for the extension-mode
counterpart of this wiring). Not part of the installable extension
package (see pyproject.toml's only-include=["extensions"]) -- this
file only matters for running epaper-nice by itself.
"""
from pathlib import Path
from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from nicegui import ui
from pydantic_settings import BaseSettings

from extensions.epaper.api.endpoints import build_standalone_router
from extensions.epaper.config import load_global_config
from extensions.epaper.paths import EpaperPaths
from extensions.epaper.ui.standalone import register_standalone_pages


class _StandaloneSettings(BaseSettings):
    """NiceGUI browser session storage secret -- standalone-only (nice4iot
    owns its own ui.run_with() and its own storage secret when running as
    an extension), so this deliberately stays out of GlobalConfig rather
    than being a user-editable/persisted extension setting. Override via
    the STORAGE_SECRET environment variable in production."""
    storage_secret: str = "geheim"


_standalone_settings = _StandaloneSettings()

# single fixed root for standalone mode, same data/ layout as before the
# nice4iot-extension split
STANDALONE_PATHS = EpaperPaths(root=Path("data"))
STANDALONE_PATHS.ensure_dirs()

load_global_config(STANDALONE_PATHS.root / "global_config.json")

# No CORS middleware: the UI is served same-origin behind the reverse
# proxy and the e-paper displays are not browsers, so nothing needs
# cross-origin access.
app = FastAPI(
    title="Epaper Doorsign Manager",
    description=(
        "Renders screens (e.g. door signs with room calendars) as PNG images "
        "for e-paper displays.\n\n"
        "Displays poll `/api/screen/{id}/image.png` and should send the last "
        "`ETag` as `If-None-Match` and respect `Cache-Control: max-age` to "
        "avoid unnecessary downloads. Screens and update schedules are "
        "managed as JSON files via the NiceGUI frontend at `/ui`."
    ),
)

app.include_router(build_standalone_router(STANDALONE_PATHS), prefix="/api")


@app.get("/", include_in_schema=False)
def redirect_to_ui():
    # the NiceGUI pages live under /ui (see mount_path below), so the bare
    # root would otherwise 404 -- there's no @app route for it at all
    return RedirectResponse(url="/ui")


register_standalone_pages(STANDALONE_PATHS, image_base_url="/../api/screen")
# docs endpoint generated by FastAPI
ui.run_with(app, mount_path="/ui", storage_secret=_standalone_settings.storage_secret)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
