"""
Storage for rooms: one JSON file per room in EpaperPaths.room_dir, named by
the room's stable surrogate id (RoomModel.id), which is also what device
bindings reference. The id never changes, so a room can be renamed freely
by editing room_name/room_number.

Thin helpers over niceview's JsonAdapter (the same per-file adapter the
screen editor uses); the room form autosaves through its own JsonAdapter,
these cover the collection: list, read, create, delete. RoomsAdapter wraps
them as a niceview CollectionAdapter so the UI is a plain DrillDownWrapper +
ModelForm rather than hand-built list/detail chrome.
"""
from typing import Iterator, Optional

from niceview import JsonAdapter

from extensions.epaper.models.room import RoomModel
from extensions.epaper.paths import EpaperPaths
from extensions.epaper.util import logger


def room_path(paths: EpaperPaths, room_id: str):
    return paths.room_dir / f'{room_id}.json'


def room_adapter(paths: EpaperPaths, room_id: str) -> JsonAdapter:
    """JsonAdapter the room form autosaves through. create_if_not_exist is
    off so merely opening a missing id can't write a junk file whose
    generated id would not match its name (see RoomModel.id)."""
    return JsonAdapter(RoomModel, room_path(paths, room_id), create_if_not_exist=False)


def list_rooms(paths: EpaperPaths) -> list[RoomModel]:
    """Every room, sorted by name then number for a stable, human list order."""
    rooms = []
    for p in sorted(paths.room_dir.glob('*.json')):
        try:
            rooms.append(JsonAdapter(RoomModel, p, create_if_not_exist=False).read())
        except Exception as e:  # skip an unreadable file rather than break the list
            logger.warning(f"Skipping unreadable room {p}: {e}")
    return sorted(rooms, key=lambda r: (r.room_name.lower(), r.room_number))


def read_room(paths: EpaperPaths, room_id: str) -> Optional[RoomModel]:
    """The room with this id, or None if there is no such file."""
    if not room_path(paths, room_id).exists():
        return None
    return room_adapter(paths, room_id).read()


def create_room(paths: EpaperPaths) -> RoomModel:
    """Create a new room with a fresh id and default fields, and return it.
    The file is named by the generated id, so it matches RoomModel.id."""
    room = RoomModel()
    room_adapter(paths, room.id).save(room)
    return room


def delete_room(paths: EpaperPaths, room_id: str) -> None:
    """Remove a room's file. Device bindings that still reference it are left
    dangling on purpose (flagged in the device card), not silently rewritten."""
    room_path(paths, room_id).unlink(missing_ok=True)


class RoomsAdapter:
    """niceview CollectionAdapter[RoomModel] over the room directory, keyed by
    RoomModel.id. Duck-typed (CollectionAdapter is a Protocol): it gives
    DrillDownWrapper its list/add/delete and ModelForm.from_adapter its
    read/update, so the rooms UI needs no bespoke CRUD chrome.

    create() persists the item as given -- the key is item.id, generated by
    RoomModel's default_factory, so the wrapper's default Add
    (adapter.create(RoomModel())) already yields a fresh id and file."""

    def __init__(self, paths: EpaperPaths) -> None:
        self._paths = paths

    def __iter__(self) -> Iterator[RoomModel]:
        return iter(list_rooms(self._paths))

    def key_from_item(self, item: RoomModel) -> str:
        return item.id

    def read(self, key: str) -> RoomModel:
        room = read_room(self._paths, key)
        if room is None:
            raise KeyError(key)
        return room

    def create(self, item: RoomModel) -> RoomModel:
        room_adapter(self._paths, item.id).save(item)
        return item

    def update(self, item: RoomModel) -> RoomModel:
        room_adapter(self._paths, item.id).save(item)
        return item

    def delete(self, key: str) -> None:
        delete_room(self._paths, key)

    def items(self) -> Iterator[tuple[str, RoomModel]]:
        for room in list_rooms(self._paths):
            yield room.id, room
