#ifndef HUFFMAN_DE_H
#define HUFFMAN_DE_H

/* Generated by extensions/epaper/wire/huffman_de.py -- do not edit by
 * hand, regenerate instead. Fixed German-text Huffman codebook, see
 * that module's docstring for the wire format this decodes.
 *
 * Decode-only: encoding happens server-side (epaper-nice); firmware
 * only needs to turn received bytes back into a string. */

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    HUFFMAN_DE_CHAR,
    HUFFMAN_DE_ESCAPE,
    HUFFMAN_DE_END,
} huffman_de_kind_t;

typedef struct {
    huffman_de_kind_t kind;
    uint8_t utf8[4];
    uint8_t utf8_len;
    uint32_t code;
    uint8_t length;
} huffman_de_symbol_t;

#define HUFFMAN_DE_TABLE_SIZE 88
extern const huffman_de_symbol_t HUFFMAN_DE_TABLE[HUFFMAN_DE_TABLE_SIZE];

/* Decodes `data` (byte_len bytes) into `out` (out_size bytes,
 * NUL-terminated). Returns the decoded length (excl. NUL), or -1 on
 * a malformed stream or if `out` is too small. */
int huffman_de_decode(const uint8_t *data, size_t byte_len,
                       char *out, size_t out_size);

#ifdef __cplusplus
}
#endif

#endif /* HUFFMAN_DE_H */
